  
name: Build ESP-AT Project

on: push

jobs:
  build-esp32c2-2mb-at:
    uses: ./.github/workflows/build_template_esp32c2.yml
    with:
      module_name: ESP32C2-2MB
      artifacts_name: esp32c2-2MB-at
    secrets: inherit
